# 地址配置
HOST = "0.0.0.0"
PORT = 8080

# 环境设置
# prod(发布) test(测试) dev(开发)
ENV = "dev"

# CORS 设置
CORS_ORIGIN_URL = "*"

# MYSQL 数据库DSN
MYSQL_DSN = "root:Xr111900@tcp(rm-wz9p9wn6719qplwioho.mysql.rds.aliyuncs.com:3306)/bot?charset=utf8"

# Token 长度. 越长越不容易重复, 导致加入公众号时出现问题
# Max 48
TOKEN_LENGTH = 6

# 管理Token, 任何非安全请求，都需要使用此管理token进行访问，否则出错

# 机器人设置
[bot]
name = "孔祥瑞"
email = "xiangrui@aiursoft.com"
password = "Xr111900"
kahlaserver = "https://staging.server.kahla.app"
callbackserver = ""
messagecallbackendpoint = ""