# 地址配置
HOST = "0.0.0.0"
PORT = 8080

# 环境设置
# prod(发布) test(测试) dev(开发)
ENV = "dev"

# 机器人设置
[bot]
name = "孔祥瑞"
email = "xiangrui@aiursoft.com"
password = "Xr111900"
kahlaserver = "https://staging.server.kahla.app"
callbackserver = ""
messagecallbackendpoint = ""