// Code generated by go-rest-client. DO NOT EDIT.
// source: events.proto
package pusher

import ()

type Pusher_EventType int32

const (
	Pusher_EventType_NewMessage       int32 = 0
	Pusher_EventType_NewFriendRequest int32 = 1
	Pusher_EventType_WereDeleted      int32 = 2
	Pusher_EventType_FriendAccepted   int32 = 3
	Pusher_EventType_TimerUpdated     int32 = 4
	Pusher_EventType_NewMember        int32 = 5
	Pusher_EventType_SomeoneLeft      int32 = 6
	Pusher_EventType_Dissolve         int32 = 7
)

var Pusher_EventType_name = map[int32]string{
	0: "NewMessage",
	1: "NewFriendRequest",
	2: "WereDeleted",
	3: "FriendAccepted",
	4: "TimerUpdated",
	5: "NewMember",
	6: "SomeoneLeft",
	7: "Dissolve",
}
var Pusher_EventType_value = map[string]int32{
	"NewMessage":       0,
	"NewFriendRequest": 1,
	"WereDeleted":      2,
	"FriendAccepted":   3,
	"TimerUpdated":     4,
	"NewMember":        5,
	"SomeoneLeft":      6,
	"Dissolve":         7,
}

type Pusher_Event struct {
	Type            uint32 `json:"type,omitempty"`
	TypeDescription string `json:"typeDescription,omitempty"`
}

type Pusher_NewMessageEvent struct {
	Type            uint32                        `json:"type,omitempty"`
	TypeDescription string                        `json:"typeDescription,omitempty"`
	ConversationId  uint32                        `json:"conversationId,omitempty"`
	Sender          Pusher_NewMessageEvent_Sender `json:"sender,omitempty"`
	Content         string                        `json:"content,omitempty"`
	AesKey          string                        `json:"aesKey,omitempty"`
	Muted           bool                          `json:"muted,omitempty"`
	Mentioned       bool                          `json:"mentioned,omitempty"`
}
type Pusher_NewMessageEvent_Sender struct {
	AccountCreateTime       string `json:"accountCreateTime,omitempty"`
	Bio                     string `json:"bio,omitempty"`
	Email                   string `json:"email,omitempty"`
	EmailConfirmed          bool   `json:"emailConfirmed,omitempty"`
	EnableEmailNotification bool   `json:"enableEmailNotification,omitempty"`
	HeadImgFileKey          uint32 `json:"headImgFileKey,omitempty"`
	Id                      string `json:"id,omitempty"`
	MakeEmailPublic         bool   `json:"makeEmailPublic,omitempty"`
	NickName                string `json:"nickName,omitempty"`
	PreferedLanguage        string `json:"preferedLanguage,omitempty"`
	Sex                     string `json:"sex,omitempty"`
	ThemeId                 uint32 `json:"themeId,omitempty"`
}

type Pusher_NewFriendRequestEvent struct {
	Type            uint32                                 `json:"type,omitempty"`
	TypeDescription string                                 `json:"typeDescription,omitempty"`
	RequesterId     string                                 `json:"requesterId,omitempty"`
	Requester       Pusher_NewFriendRequestEvent_Requester `json:"requester,omitempty"`
}
type Pusher_NewFriendRequestEvent_Requester struct {
	AccountCreateTime       string `json:"accountCreateTime,omitempty"`
	Bio                     string `json:"bio,omitempty"`
	Email                   string `json:"email,omitempty"`
	EmailConfirmed          bool   `json:"emailConfirmed,omitempty"`
	EnableEmailNotification bool   `json:"enableEmailNotification,omitempty"`
	HeadImgFileKey          uint32 `json:"headImgFileKey,omitempty"`
	Id                      string `json:"id,omitempty"`
	MakeEmailPublic         bool   `json:"makeEmailPublic,omitempty"`
	NickName                string `json:"nickName,omitempty"`
	PreferedLanguage        string `json:"preferedLanguage,omitempty"`
	Sex                     string `json:"sex,omitempty"`
	ThemeId                 uint32 `json:"themeId,omitempty"`
}

type Pusher_WereDeletedEvent struct {
	Type            uint32                          `json:"type,omitempty"`
	TypeDescription string                          `json:"typeDescription,omitempty"`
	Trigger         Pusher_WereDeletedEvent_Trigger `json:"trigger,omitempty"`
}
type Pusher_WereDeletedEvent_Trigger struct {
	AccountCreateTime       string `json:"accountCreateTime,omitempty"`
	Bio                     string `json:"bio,omitempty"`
	Email                   string `json:"email,omitempty"`
	EmailConfirmed          bool   `json:"emailConfirmed,omitempty"`
	EnableEmailNotification bool   `json:"enableEmailNotification,omitempty"`
	HeadImgFileKey          uint32 `json:"headImgFileKey,omitempty"`
	Id                      string `json:"id,omitempty"`
	MakeEmailPublic         bool   `json:"makeEmailPublic,omitempty"`
	NickName                string `json:"nickName,omitempty"`
	PreferedLanguage        string `json:"preferedLanguage,omitempty"`
	Sex                     string `json:"sex,omitempty"`
	ThemeId                 uint32 `json:"themeId,omitempty"`
}

type Pusher_FriendAcceptedEvent struct {
	Type            uint32                            `json:"type,omitempty"`
	TypeDescription string                            `json:"typeDescription,omitempty"`
	Target          Pusher_FriendAcceptedEvent_Target `json:"target,omitempty"`
}
type Pusher_FriendAcceptedEvent_Target struct {
	AccountCreateTime       string `json:"accountCreateTime,omitempty"`
	Bio                     string `json:"bio,omitempty"`
	Email                   string `json:"email,omitempty"`
	EmailConfirmed          bool   `json:"emailConfirmed,omitempty"`
	EnableEmailNotification bool   `json:"enableEmailNotification,omitempty"`
	HeadImgFileKey          uint32 `json:"headImgFileKey,omitempty"`
	Id                      string `json:"id,omitempty"`
	MakeEmailPublic         bool   `json:"makeEmailPublic,omitempty"`
	NickName                string `json:"nickName,omitempty"`
	PreferedLanguage        string `json:"preferedLanguage,omitempty"`
	Sex                     string `json:"sex,omitempty"`
	ThemeId                 uint32 `json:"themeId,omitempty"`
}

type Pusher_TimerUpdatedEvent struct {
	Type            uint32 `json:"type,omitempty"`
	TypeDescription string `json:"typeDescription,omitempty"`
	ConversationId  uint32 `json:"conversationId,omitempty"`
	NewTimer        uint32 `json:"newTimer,omitempty"`
}

type Pusher_NewMemberEvent struct {
	Type            uint32                          `json:"type,omitempty"`
	TypeDescription string                          `json:"typeDescription,omitempty"`
	ConversationId  uint32                          `json:"conversationId,omitempty"`
	NewMember       Pusher_NewMemberEvent_NewMember `json:"newMember,omitempty"`
}
type Pusher_NewMemberEvent_NewMember struct {
	AccountCreateTime       string `json:"accountCreateTime,omitempty"`
	Bio                     string `json:"bio,omitempty"`
	Email                   string `json:"email,omitempty"`
	EmailConfirmed          bool   `json:"emailConfirmed,omitempty"`
	EnableEmailNotification bool   `json:"enableEmailNotification,omitempty"`
	HeadImgFileKey          uint32 `json:"headImgFileKey,omitempty"`
	Id                      string `json:"id,omitempty"`
	MakeEmailPublic         bool   `json:"makeEmailPublic,omitempty"`
	NickName                string `json:"nickName,omitempty"`
	PreferedLanguage        string `json:"preferedLanguage,omitempty"`
	Sex                     string `json:"sex,omitempty"`
	ThemeId                 uint32 `json:"themeId,omitempty"`
}

type Pusher_SomeoneLeftEvent struct {
	Type            uint32                           `json:"type,omitempty"`
	TypeDescription string                           `json:"typeDescription,omitempty"`
	ConversationId  uint32                           `json:"conversationId,omitempty"`
	LeftUser        Pusher_SomeoneLeftEvent_LeftUser `json:"leftUser,omitempty"`
}
type Pusher_SomeoneLeftEvent_LeftUser struct {
	AccountCreateTime       string `json:"accountCreateTime,omitempty"`
	Bio                     string `json:"bio,omitempty"`
	Email                   string `json:"email,omitempty"`
	EmailConfirmed          bool   `json:"emailConfirmed,omitempty"`
	EnableEmailNotification bool   `json:"enableEmailNotification,omitempty"`
	HeadImgFileKey          uint32 `json:"headImgFileKey,omitempty"`
	Id                      string `json:"id,omitempty"`
	MakeEmailPublic         bool   `json:"makeEmailPublic,omitempty"`
	NickName                string `json:"nickName,omitempty"`
	PreferedLanguage        string `json:"preferedLanguage,omitempty"`
	Sex                     string `json:"sex,omitempty"`
	ThemeId                 uint32 `json:"themeId,omitempty"`
}

type Pusher_DissolveEvent struct {
	Type            uint32 `json:"type,omitempty"`
	TypeDescription string `json:"typeDescription,omitempty"`
	ConversationId  uint32 `json:"conversationId,omitempty"`
}
